export const PLATFORM = {
    CHROME: 'CHROME',
    FIREFOX: 'FIREFOX',
    IE: 'IE',
    EDGE: 'EDGE',
    OPERA: 'OPERA',
    SAFARI: 'SAFARI',
    PHANTOMJS: 'PHANTOMJS',
    HTMLUNITWITHJS: 'HTMLUNITWITHJS',
    ANDROID: 'ANDROID',
    IPHONE: 'IPHONE',
    IPAD: 'IPAD'
};
